CREATE TABLE IF NOT EXISTS tunnel_client_account (
  id BIGINT PRIMARY KEY,
  tenant_id VARCHAR(80) NOT NULL DEFAULT 'default',
  owner_username VARCHAR(80),
  client_name VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(64) NOT NULL,
  enabled SMALLINT NOT NULL,
  connection_rate_limit_per_minute INTEGER NOT NULL,
  created_at VARCHAR(40) NOT NULL,
  updated_at VARCHAR(40) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tunnel_client_tenant ON tunnel_client_account (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tunnel_client_owner ON tunnel_client_account (tenant_id, owner_username);

CREATE TABLE IF NOT EXISTS tunnel_client_credential (
  id BIGINT PRIMARY KEY,
  tenant_id VARCHAR(80) NOT NULL,
  owner_username VARCHAR(80),
  api_key VARCHAR(120) NOT NULL UNIQUE,
  secret_hash VARCHAR(64) NOT NULL,
  enabled SMALLINT NOT NULL,
  max_online_instances INTEGER NOT NULL,
  created_at VARCHAR(40) NOT NULL,
  updated_at VARCHAR(40) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_client_credential_tenant ON tunnel_client_credential (tenant_id);
CREATE INDEX IF NOT EXISTS idx_client_credential_owner ON tunnel_client_credential (tenant_id, owner_username);

CREATE TABLE IF NOT EXISTS tunnel_client_identity (
  id BIGINT PRIMARY KEY,
  tenant_id VARCHAR(80) NOT NULL,
  credential_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  client_name VARCHAR(120) NOT NULL,
  machine_fingerprint VARCHAR(160) NOT NULL,
  os_user VARCHAR(120) NOT NULL,
  hostname VARCHAR(160),
  first_seen_at VARCHAR(40) NOT NULL,
  last_seen_at VARCHAR(40) NOT NULL,
  UNIQUE (credential_id, machine_fingerprint, os_user)
);

CREATE INDEX IF NOT EXISTS idx_client_identity_tenant ON tunnel_client_identity (tenant_id);
CREATE INDEX IF NOT EXISTS idx_client_identity_client ON tunnel_client_identity (client_id);

CREATE TABLE IF NOT EXISTS tunnel_connection_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT,
  client_name VARCHAR(120) NOT NULL,
  channel_id VARCHAR(160),
  remote_address VARCHAR(255),
  connected_at VARCHAR(40) NOT NULL,
  disconnected_at VARCHAR(40),
  success SMALLINT NOT NULL,
  failure_reason VARCHAR(255),
  disconnect_reason VARCHAR(40)
);

CREATE INDEX IF NOT EXISTS idx_tunnel_connection_client_time ON tunnel_connection_record (client_id, connected_at);
CREATE INDEX IF NOT EXISTS idx_tunnel_connection_connected_at ON tunnel_connection_record (connected_at);

CREATE TABLE IF NOT EXISTS tunnel_mapping (
  id BIGINT PRIMARY KEY,
  client_id BIGINT NOT NULL,
  client_name VARCHAR(120) NOT NULL,
  listen_port INTEGER NOT NULL UNIQUE,
  target_address VARCHAR(255) NOT NULL,
  target_port INTEGER NOT NULL,
  enabled SMALLINT NOT NULL,
  created_at VARCHAR(40) NOT NULL,
  updated_at VARCHAR(40) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tunnel_mapping_client_id ON tunnel_mapping (client_id);

CREATE TABLE IF NOT EXISTS http_route_mapping (
  id BIGINT PRIMARY KEY,
  client_id BIGINT NOT NULL,
  client_name VARCHAR(120) NOT NULL,
  route VARCHAR(60) NOT NULL,
  target_base_url VARCHAR(512) NOT NULL,
  enabled SMALLINT NOT NULL,
  created_at VARCHAR(40) NOT NULL,
  updated_at VARCHAR(40) NOT NULL,
  UNIQUE (client_id, route)
);

CREATE INDEX IF NOT EXISTS idx_http_route_client_id ON http_route_mapping (client_id);

CREATE TABLE IF NOT EXISTS tunnel_traffic_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL,
  client_name VARCHAR(120) NOT NULL,
  usage_date VARCHAR(10) NOT NULL,
  upload_bytes BIGINT NOT NULL,
  download_bytes BIGINT NOT NULL,
  updated_at VARCHAR(40) NOT NULL,
  UNIQUE (client_id, usage_date)
);

CREATE INDEX IF NOT EXISTS idx_traffic_client_id ON tunnel_traffic_usage (client_id);

CREATE TABLE IF NOT EXISTS tunnel_connection_stat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT,
  client_name VARCHAR(120) NOT NULL,
  stat_month VARCHAR(7) NOT NULL,
  total_count BIGINT NOT NULL,
  success_count BIGINT NOT NULL,
  failure_count BIGINT NOT NULL,
  updated_at VARCHAR(40) NOT NULL,
  UNIQUE (client_name, stat_month)
);

CREATE INDEX IF NOT EXISTS idx_stat_client_name ON tunnel_connection_stat (client_name);
