#define _POSIX_C_SOURCE 200809L

/*
 * OIDC login against a fake identity provider on 127.0.0.1: a JWKS endpoint and a token endpoint
 * that hands out one-time authorization codes, with RSA and EC keys generated by OpenSSL at run
 * time. Java's flow has no discovery request, so the fake has no discovery document either.
 * Mirrors OidcControllerTests, SecurityConfigOidcTests, ManagementContextResolverTests and the
 * OIDC cases of ManagementUserServiceTests on the Java server.
 */

#include "admin_http.h"
#include "json.h"
#include "oidc.h"
#include "password_hash.h"
#include "security.h"
#include "storage.h"

#include <arpa/inet.h>
#include <errno.h>
#include <netinet/in.h>
#include <openssl/bn.h>
#include <openssl/core_names.h>
#include <openssl/ec.h>
#include <openssl/evp.h>
#include <openssl/hmac.h>
#include <openssl/x509.h>
#include <pthread.h>
#include <sqlite3.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>

#define CLIENT_ID "specus-admin"
#define RESOURCE_AUDIENCE "specus-api"
#define JWT_SECRET "oidc-tests-jwt-secret"
#define VERIFIER "verifier-value"
/* The admin listener answers from a 32 KiB buffer; use the same here. */
#define RESPONSE_CAP 32768U
#define IDP_MAX_CODES 256U

typedef struct {
    char code[64];
    int status;
    char *body;
    int used;
} idp_code;

typedef struct {
    int fd;
    int port;
    pthread_t thread;
    pthread_mutex_t lock;
    int stop;
    char *jwks;
    int jwks_status;
    int jwks_hits;
    int token_requests;
    char *last_token_request;
    idp_code codes[IDP_MAX_CODES];
    size_t code_count;
} fake_idp;

typedef struct {
    const char *iss;
    const char *sub;
    const char *aud;   /* raw JSON value; NULL omits the claim */
    const char *azp;
    const char *nonce;
    const char *preferred_username;
    long long exp_offset;
    int omit_exp;
    const char *exp_raw; /* raw JSON value replacing the computed exp */
    int has_nbf;
    long long nbf_offset;
    const char *extra; /* raw members appended to the claims object */
} claims_spec;

static fake_idp idp;
static char issuer[64];
static char db_path[512];
static char response[RESPONSE_CAP];
static EVP_PKEY *key_main;
static EVP_PKEY *key_next;
static EVP_PKEY *key_attacker;
static EVP_PKEY *key_weak;
static EVP_PKEY *key_ec;
static char *jwk_main;
static char *jwk_next;
static char *jwk_weak;
static char *jwk_ec;
static int code_counter;
static int checks;
static int failures;

#define CHECK(condition, message) \
    do { \
        ++checks; \
        if (!(condition)) { \
            fprintf(stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__, (message)); \
            ++failures; \
        } \
    } while (0)

static char *format(const char *pattern, ...)
{
    va_list args;
    va_start(args, pattern);
    va_list copy;
    va_copy(copy, args);
    int needed = vsnprintf(NULL, 0, pattern, copy);
    va_end(copy);
    char *out = needed < 0 ? NULL : (char *)malloc((size_t)needed + 1U);
    if (out != NULL) {
        vsnprintf(out, (size_t)needed + 1U, pattern, args);
    }
    va_end(args);
    if (out == NULL) {
        fprintf(stderr, "out of memory\n");
        exit(2);
    }
    return out;
}

static char *duplicate(const char *text)
{
    return format("%s", text);
}

static int contains(const char *haystack, const char *needle)
{
    return haystack != NULL && strstr(haystack, needle) != NULL;
}

static char *base64url(const uint8_t *data, size_t len)
{
    static const char alphabet[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    char *out = (char *)malloc(len / 3U * 4U + 5U);
    if (out == NULL) {
        exit(2);
    }
    size_t written = 0U;
    uint32_t acc = 0U;
    unsigned int bits = 0U;
    for (size_t i = 0U; i < len; ++i) {
        acc = (acc << 8U) | data[i];
        bits += 8U;
        while (bits >= 6U) {
            bits -= 6U;
            out[written++] = alphabet[(acc >> bits) & 0x3fU];
        }
    }
    if (bits > 0U) {
        out[written++] = alphabet[(acc << (6U - bits)) & 0x3fU];
    }
    out[written] = '\0';
    return out;
}

static char *base64url_text(const char *text)
{
    return base64url((const uint8_t *)text, strlen(text));
}

/* ---- fake identity provider --------------------------------------------------------------- */

static int idp_read_request(int client, char *buffer, size_t cap, size_t *len)
{
    *len = 0U;
    size_t header_end = 0U;
    size_t content_length = 0U;
    for (;;) {
        if (*len + 1U >= cap) {
            return -1;
        }
        ssize_t got = recv(client, buffer + *len, cap - 1U - *len, 0);
        if (got <= 0) {
            return -1;
        }
        *len += (size_t)got;
        buffer[*len] = '\0';
        if (header_end == 0U) {
            char *end = strstr(buffer, "\r\n\r\n");
            if (end != NULL) {
                header_end = (size_t)(end - buffer) + 4U;
                const char *length = strstr(buffer, "Content-Length:");
                if (length != NULL && length < end) {
                    content_length = (size_t)strtoul(length + strlen("Content-Length:"), NULL, 10);
                }
            }
        }
        if (header_end != 0U && *len >= header_end + content_length) {
            return 0;
        }
    }
}

static void idp_respond(int client, int status, const char *body)
{
    const char *reason = status == 200 ? "OK" : status == 400 ? "Bad Request" : status == 404 ? "Not Found" : "Error";
    char *message = format("HTTP/1.1 %d %s\r\n"
                           "Content-Type: application/json\r\n"
                           "Content-Length: %zu\r\n"
                           "Connection: close\r\n"
                           "\r\n"
                           "%s",
                           status,
                           reason,
                           strlen(body),
                           body);
    size_t sent = 0U;
    size_t total = strlen(message);
    while (sent < total) {
        ssize_t wrote = send(client, message + sent, total - sent, 0);
        if (wrote <= 0) {
            break;
        }
        sent += (size_t)wrote;
    }
    free(message);
}

static void idp_handle(int client)
{
    size_t cap = 65536U;
    char *request = (char *)malloc(cap);
    size_t len = 0U;
    if (request == NULL || idp_read_request(client, request, cap, &len) != 0) {
        free(request);
        return;
    }
    if (strncmp(request, "GET /jwks ", strlen("GET /jwks ")) == 0) {
        pthread_mutex_lock(&idp.lock);
        int status = idp.jwks_status;
        char *body = duplicate(status == 200 ? idp.jwks : "{\"error\":\"unavailable\"}");
        ++idp.jwks_hits;
        pthread_mutex_unlock(&idp.lock);
        idp_respond(client, status, body);
        free(body);
    } else if (strncmp(request, "POST /token ", strlen("POST /token ")) == 0) {
        const char *form = strstr(request, "\r\n\r\n") + 4;
        char code[64] = "";
        const char *code_param = strstr(form, "&code=");
        if (code_param != NULL) {
            code_param += strlen("&code=");
            size_t code_len = strcspn(code_param, "&");
            if (code_len < sizeof(code)) {
                memcpy(code, code_param, code_len);
                code[code_len] = '\0';
            }
        }
        pthread_mutex_lock(&idp.lock);
        ++idp.token_requests;
        free(idp.last_token_request);
        idp.last_token_request = duplicate(request);
        /* Authorization codes are single use, as at a real identity provider. */
        int status = 400;
        char *body = NULL;
        for (size_t i = 0U; i < idp.code_count; ++i) {
            if (strcmp(idp.codes[i].code, code) == 0 && !idp.codes[i].used) {
                idp.codes[i].used = 1;
                status = idp.codes[i].status;
                body = duplicate(idp.codes[i].body);
                break;
            }
        }
        pthread_mutex_unlock(&idp.lock);
        if (body == NULL) {
            body = duplicate("{\"error\":\"invalid_grant\","
                             "\"error_description\":\"authorization code is invalid or already used\"}");
        }
        idp_respond(client, status, body);
        free(body);
    } else {
        idp_respond(client, 404, "{\"error\":\"not_found\"}");
    }
    free(request);
}

static void *idp_main(void *arg)
{
    (void)arg;
    for (;;) {
        int client = accept(idp.fd, NULL, NULL);
        pthread_mutex_lock(&idp.lock);
        int stop = idp.stop;
        pthread_mutex_unlock(&idp.lock);
        if (stop) {
            if (client >= 0) {
                close(client);
            }
            return NULL;
        }
        if (client < 0) {
            if (errno == EINTR) {
                continue;
            }
            return NULL;
        }
        struct timeval timeout = {5, 0};
        (void)setsockopt(client, SOL_SOCKET, SO_RCVTIMEO, &timeout, sizeof(timeout));
        idp_handle(client);
        close(client);
    }
}

static int idp_start(void)
{
    memset(&idp, 0, sizeof(idp));
    pthread_mutex_init(&idp.lock, NULL);
    idp.jwks = duplicate("{\"keys\":[]}");
    idp.jwks_status = 200;
    idp.fd = socket(AF_INET, SOCK_STREAM, 0);
    if (idp.fd < 0) {
        return -1;
    }
    struct sockaddr_in address;
    memset(&address, 0, sizeof(address));
    address.sin_family = AF_INET;
    address.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    address.sin_port = 0;
    socklen_t address_len = sizeof(address);
    if (bind(idp.fd, (struct sockaddr *)&address, sizeof(address)) != 0
        || listen(idp.fd, 16) != 0
        || getsockname(idp.fd, (struct sockaddr *)&address, &address_len) != 0) {
        close(idp.fd);
        return -1;
    }
    idp.port = ntohs(address.sin_port);
    return pthread_create(&idp.thread, NULL, idp_main, NULL) == 0 ? 0 : -1;
}

static void idp_stop(void)
{
    pthread_mutex_lock(&idp.lock);
    idp.stop = 1;
    pthread_mutex_unlock(&idp.lock);
    int wake = socket(AF_INET, SOCK_STREAM, 0);
    if (wake >= 0) {
        struct sockaddr_in address;
        memset(&address, 0, sizeof(address));
        address.sin_family = AF_INET;
        address.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
        address.sin_port = htons((uint16_t)idp.port);
        (void)connect(wake, (struct sockaddr *)&address, sizeof(address));
        close(wake);
    }
    pthread_join(idp.thread, NULL);
    close(idp.fd);
    for (size_t i = 0U; i < idp.code_count; ++i) {
        free(idp.codes[i].body);
    }
    free(idp.jwks);
    free(idp.last_token_request);
    pthread_mutex_destroy(&idp.lock);
}

static void idp_add_code(const char *code, int status, const char *body)
{
    pthread_mutex_lock(&idp.lock);
    if (idp.code_count < IDP_MAX_CODES) {
        idp_code *entry = &idp.codes[idp.code_count++];
        snprintf(entry->code, sizeof(entry->code), "%s", code);
        entry->status = status;
        entry->body = duplicate(body);
        entry->used = 0;
    }
    pthread_mutex_unlock(&idp.lock);
}

static void idp_set_jwks(const char *jwks, int status)
{
    pthread_mutex_lock(&idp.lock);
    free(idp.jwks);
    idp.jwks = duplicate(jwks);
    idp.jwks_status = status;
    pthread_mutex_unlock(&idp.lock);
}

static void idp_publish(const char *first, const char *second, const char *third, const char *fourth)
{
    const char *entries[4] = {first, second, third, fourth};
    char *jwks = duplicate("{\"keys\":[");
    int any = 0;
    for (size_t i = 0U; i < 4U; ++i) {
        if (entries[i] == NULL) {
            continue;
        }
        char *next = format("%s%s%s", jwks, any ? "," : "", entries[i]);
        free(jwks);
        jwks = next;
        any = 1;
    }
    char *closed = format("%s]}", jwks);
    idp_set_jwks(closed, 200);
    free(jwks);
    free(closed);
}

static int idp_jwks_hits(void)
{
    pthread_mutex_lock(&idp.lock);
    int hits = idp.jwks_hits;
    pthread_mutex_unlock(&idp.lock);
    return hits;
}

static int idp_token_requests(void)
{
    pthread_mutex_lock(&idp.lock);
    int requests = idp.token_requests;
    pthread_mutex_unlock(&idp.lock);
    return requests;
}

static char *idp_last_token_request(void)
{
    pthread_mutex_lock(&idp.lock);
    char *request = duplicate(idp.last_token_request == NULL ? "" : idp.last_token_request);
    pthread_mutex_unlock(&idp.lock);
    return request;
}

/* ---- keys and tokens ------------------------------------------------------------------------ */

static EVP_PKEY *rsa_key(unsigned int bits)
{
    EVP_PKEY *key = EVP_PKEY_Q_keygen(NULL, NULL, "RSA", (size_t)bits);
    if (key == NULL) {
        fprintf(stderr, "RSA key generation failed\n");
        exit(2);
    }
    return key;
}

static EVP_PKEY *ec_key(void)
{
    EVP_PKEY *key = EVP_PKEY_Q_keygen(NULL, NULL, "EC", "P-256");
    if (key == NULL) {
        fprintf(stderr, "EC key generation failed\n");
        exit(2);
    }
    return key;
}

static char *bn_param(EVP_PKEY *key, const char *name, int pad)
{
    BIGNUM *value = NULL;
    if (EVP_PKEY_get_bn_param(key, name, &value) != 1) {
        fprintf(stderr, "key parameter %s unavailable\n", name);
        exit(2);
    }
    int len = pad > 0 ? pad : BN_num_bytes(value);
    uint8_t *bytes = (uint8_t *)malloc((size_t)len);
    if (bytes == NULL || (pad > 0 ? BN_bn2binpad(value, bytes, pad) : BN_bn2bin(value, bytes)) != len) {
        exit(2);
    }
    char *encoded = base64url(bytes, (size_t)len);
    free(bytes);
    BN_free(value);
    return encoded;
}

static char *rsa_jwk(EVP_PKEY *key, const char *kid)
{
    char *n = bn_param(key, OSSL_PKEY_PARAM_RSA_N, 0);
    char *e = bn_param(key, OSSL_PKEY_PARAM_RSA_E, 0);
    char *jwk = format("{\"kty\":\"RSA\",\"kid\":\"%s\",\"use\":\"sig\",\"alg\":\"RS256\",\"n\":\"%s\",\"e\":\"%s\"}",
                       kid, n, e);
    free(n);
    free(e);
    return jwk;
}

static char *ec_jwk(EVP_PKEY *key, const char *kid)
{
    char *x = bn_param(key, OSSL_PKEY_PARAM_EC_PUB_X, 32);
    char *y = bn_param(key, OSSL_PKEY_PARAM_EC_PUB_Y, 32);
    char *jwk = format("{\"kty\":\"EC\",\"kid\":\"%s\",\"use\":\"sig\",\"alg\":\"ES256\",\"crv\":\"P-256\","
                       "\"x\":\"%s\",\"y\":\"%s\"}",
                       kid, x, y);
    free(x);
    free(y);
    return jwk;
}

static char *signing_input(const char *header_json, const char *payload_json)
{
    char *header = base64url_text(header_json);
    char *payload = base64url_text(payload_json);
    char *input = format("%s.%s", header, payload);
    free(header);
    free(payload);
    return input;
}

/* RS256 with an RSA key, ES256 (JOSE r||s) with an EC key. */
static char *sign_jwt(EVP_PKEY *key, const char *header_json, const char *payload_json)
{
    char *input = signing_input(header_json, payload_json);
    EVP_MD_CTX *context = EVP_MD_CTX_new();
    size_t signature_len = 0U;
    uint8_t *signature = NULL;
    if (context == NULL
        || EVP_DigestSignInit(context, NULL, EVP_sha256(), NULL, key) != 1
        || EVP_DigestSign(context, NULL, &signature_len, (const unsigned char *)input, strlen(input)) != 1
        || (signature = (uint8_t *)malloc(signature_len)) == NULL
        || EVP_DigestSign(context, signature, &signature_len, (const unsigned char *)input, strlen(input)) != 1) {
        fprintf(stderr, "signing failed\n");
        exit(2);
    }
    EVP_MD_CTX_free(context);
    char *encoded = NULL;
    if (EVP_PKEY_is_a(key, "EC")) {
        const unsigned char *cursor = signature;
        ECDSA_SIG *ecdsa = d2i_ECDSA_SIG(NULL, &cursor, (long)signature_len);
        const BIGNUM *r = NULL;
        const BIGNUM *s = NULL;
        uint8_t raw[64];
        if (ecdsa == NULL) {
            exit(2);
        }
        ECDSA_SIG_get0(ecdsa, &r, &s);
        if (BN_bn2binpad(r, raw, 32) != 32 || BN_bn2binpad(s, raw + 32, 32) != 32) {
            exit(2);
        }
        ECDSA_SIG_free(ecdsa);
        encoded = base64url(raw, sizeof(raw));
    } else {
        encoded = base64url(signature, signature_len);
    }
    char *token = format("%s.%s", input, encoded);
    free(input);
    free(signature);
    free(encoded);
    return token;
}

static char *sign_hs256(const uint8_t *secret, size_t secret_len, const char *header_json, const char *payload_json)
{
    char *input = signing_input(header_json, payload_json);
    unsigned char mac[EVP_MAX_MD_SIZE];
    unsigned int mac_len = 0U;
    if (HMAC(EVP_sha256(), secret, (int)secret_len, (const unsigned char *)input, strlen(input), mac, &mac_len) == NULL) {
        exit(2);
    }
    char *encoded = base64url(mac, mac_len);
    char *token = format("%s.%s", input, encoded);
    free(input);
    free(encoded);
    return token;
}

static claims_spec id_claims(const char *subject, const char *username, const char *nonce)
{
    claims_spec spec;
    memset(&spec, 0, sizeof(spec));
    spec.iss = issuer;
    spec.sub = subject;
    spec.aud = "\"" CLIENT_ID "\"";
    spec.nonce = nonce;
    spec.preferred_username = username;
    spec.exp_offset = 300;
    return spec;
}

static void add_member(char **json, const char *name, const char *raw_value)
{
    char *next = format("%s%s\"%s\":%s", *json, strcmp(*json, "{") == 0 ? "" : ",", name, raw_value);
    free(*json);
    *json = next;
}

static void add_string_member(char **json, const char *name, const char *value)
{
    if (value == NULL) {
        return;
    }
    char *quoted = format("\"%s\"", value);
    add_member(json, name, quoted);
    free(quoted);
}

static char *claims_json(const claims_spec *spec)
{
    long long now = (long long)time(NULL);
    char *json = duplicate("{");
    add_string_member(&json, "iss", spec->iss);
    add_string_member(&json, "sub", spec->sub);
    if (spec->aud != NULL) {
        add_member(&json, "aud", spec->aud);
    }
    add_string_member(&json, "azp", spec->azp);
    add_string_member(&json, "nonce", spec->nonce);
    add_string_member(&json, "preferred_username", spec->preferred_username);
    char *number = format("%lld", now);
    add_member(&json, "iat", number);
    free(number);
    if (spec->exp_raw != NULL) {
        add_member(&json, "exp", spec->exp_raw);
    } else if (!spec->omit_exp) {
        number = format("%lld", now + spec->exp_offset);
        add_member(&json, "exp", number);
        free(number);
    }
    if (spec->has_nbf) {
        number = format("%lld", now + spec->nbf_offset);
        add_member(&json, "nbf", number);
        free(number);
    }
    char *closed = spec->extra == NULL
        ? format("%s}", json)
        : format("%s,%s}", json, spec->extra);
    free(json);
    return closed;
}

static char *rs256_header(const char *kid)
{
    return kid == NULL
        ? duplicate("{\"alg\":\"RS256\",\"typ\":\"JWT\"}")
        : format("{\"alg\":\"RS256\",\"typ\":\"JWT\",\"kid\":\"%s\"}", kid);
}

static char *make_token(EVP_PKEY *key, const char *kid, const claims_spec *spec)
{
    char *header = rs256_header(kid);
    char *payload = claims_json(spec);
    char *token = sign_jwt(key, header, payload);
    free(header);
    free(payload);
    return token;
}

/* ---- requests ------------------------------------------------------------------------------- */

static int status_of(const char *text)
{
    int status = 0;
    return sscanf(text, "HTTP/1.1 %d", &status) == 1 ? status : -1;
}

static const char *body_of(const char *text)
{
    const char *body = strstr(text, "\r\n\r\n");
    return body == NULL ? "" : body + 4;
}

static int redeem(const char *code, const char *verifier, const char *nonce)
{
    char *request = nonce == NULL
        ? format("{\"code\":\"%s\",\"codeVerifier\":\"%s\"}", code, verifier)
        : format("{\"code\":\"%s\",\"codeVerifier\":\"%s\",\"nonce\":\"%s\"}", code, verifier, nonce);
    int len = st_admin_build_response_with_body("POST", "/oidc/token", request, response, sizeof(response));
    free(request);
    return len > 0 ? status_of(response) : -1;
}

static char *next_code(void)
{
    return format("code-%d", ++code_counter);
}

/* The browser's callback: the identity provider issues a code for id_token, the SPA redeems it. */
static int login_with(const char *id_token, const char *nonce)
{
    char *code = next_code();
    char *body = format("{\"access_token\":\"idp-access-token\",\"refresh_token\":\"idp-refresh-token\","
                        "\"id_token\":\"%s\",\"token_type\":\"Bearer\",\"expires_in\":3600}",
                        id_token);
    idp_add_code(code, 200, body);
    int status = redeem(code, VERIFIER, nonce);
    free(code);
    free(body);
    return status;
}

static int login_claims(EVP_PKEY *key, const char *kid, const claims_spec *spec)
{
    char *token = make_token(key, kid, spec);
    int status = login_with(token, spec->nonce == NULL ? "unused-nonce" : spec->nonce);
    free(token);
    return status;
}

static char *access_token_of(const char *text)
{
    return st_json_get_top_level_string(body_of(text), "accessToken");
}

static int admin_request(const char *method, const char *path, const char *token)
{
    char *authorization = format("Bearer %s", token);
    int len = st_admin_build_response_with_auth(method, path, authorization, NULL, response, sizeof(response));
    free(authorization);
    return len > 0 ? status_of(response) : -1;
}

static int local_claims_of(const char *token, st_security_token_claims *claims)
{
    return token == NULL ? -1 : st_security_validate_local_token(token, JWT_SECRET, "default", "admin", claims);
}

static char *db_text(const char *sql, const char *parameter)
{
    sqlite3 *db = NULL;
    sqlite3_stmt *stmt = NULL;
    char *result = NULL;
    if (sqlite3_open(db_path, &db) == SQLITE_OK
        && sqlite3_prepare_v2(db, sql, -1, &stmt, NULL) == SQLITE_OK) {
        sqlite3_bind_text(stmt, 1, parameter, -1, SQLITE_TRANSIENT);
        if (sqlite3_step(stmt) == SQLITE_ROW && sqlite3_column_text(stmt, 0) != NULL) {
            result = duplicate((const char *)sqlite3_column_text(stmt, 0));
        }
    }
    sqlite3_finalize(stmt);
    sqlite3_close(db);
    return result;
}

static void create_user(const char *username, const char *tenant_id, const char *role, int enabled)
{
    char hash[ST_PASSWORD_HASH_MAX_LEN + 1U];
    if (st_password_hash("local-password-123", hash) != 0
        || st_storage_create_management_user(db_path, username, tenant_id, hash, role, enabled, NULL) != 0) {
        fprintf(stderr, "cannot create user %s\n", username);
        exit(2);
    }
}

static void set_enabled(const char *username, int enabled)
{
    if (st_storage_update_management_user(db_path, "default", username, NULL, NULL, enabled, NULL) != 0) {
        fprintf(stderr, "cannot update user %s\n", username);
        exit(2);
    }
}

/* Logs in as subject/username and returns the local token, or NULL. */
static char *login_token(const char *subject, const char *username)
{
    claims_spec spec = id_claims(subject, username, "nonce-login");
    return login_claims(key_main, "k1", &spec) == 200 ? access_token_of(response) : NULL;
}

/* ---- tests ---------------------------------------------------------------------------------- */

static void test_login_issues_local_token(void)
{
    claims_spec spec = id_claims("subject-alice", "alice", "nonce-alice");
    char *id_token = make_token(key_main, "k1", &spec);
    CHECK(login_with(id_token, "nonce-alice") == 200, "OIDC login was not accepted");
    const char *body = body_of(response);
    CHECK(!contains(body, "idp-access-token") && !contains(body, "idp-refresh-token"),
          "the identity provider's tokens reached the browser");
    char *echoed = st_json_get_top_level_string(body, "idToken");
    char *token_type = st_json_get_top_level_string(body, "tokenType");
    long long expires_in = 0;
    CHECK(echoed != NULL && strcmp(echoed, id_token) == 0, "idToken is not the validated ID token");
    CHECK(token_type != NULL && strcmp(token_type, "Bearer") == 0, "tokenType mismatch");
    CHECK(st_json_get_i64(body, "expiresIn", &expires_in) == 0 && expires_in == 28800,
          "expiresIn is not the local token lifetime");
    char *access = access_token_of(response);
    st_security_token_claims claims;
    CHECK(local_claims_of(access, &claims) == 0, "accessToken is not a local HS256 token");
    CHECK(strcmp(claims.username, "alice") == 0 && strcmp(claims.tenant_id, "default") == 0
              && strcmp(claims.role, "USER") == 0,
          "local token does not name the provisioned USER");

    char *request = idp_last_token_request();
    CHECK(contains(request, "POST /token HTTP/1.1")
              && contains(request, "grant_type=authorization_code")
              && contains(request, "code_verifier=" VERIFIER)
              && contains(request, "redirect_uri=http%3A%2F%2F127.0.0.1%3A8088%2F")
              && contains(request, "client_id=" CLIENT_ID)
              && !contains(request, "Authorization: Basic"),
          "token request is not a public PKCE authorization-code request");

    CHECK(admin_request("GET", "/api/admin/me", access) == 200
              && contains(response, "\"username\":\"alice\"")
              && contains(response, "\"tenantId\":\"default\"")
              && contains(response, "\"role\":\"USER\""),
          "local token from OIDC login cannot read /api/admin/me");
    CHECK(admin_request("GET", "/api/admin/users", access) == 403,
          "OIDC-provisioned USER reached an admin-only endpoint");
    CHECK(admin_request("POST", "/auth/refresh", access) == 200 && contains(response, "\"accessToken\""),
          "local token from OIDC login cannot be refreshed like a password-login token");

    char expected_key[65];
    CHECK(st_oidc_identity_key(issuer, "subject-alice", expected_key) == 0, "identity key failed");
    char *stored_key = db_text("SELECT oidc_identity_key FROM specus_management_user WHERE username = ?", "alice");
    char *stored_issuer = db_text("SELECT oidc_issuer FROM specus_management_user WHERE username = ?", "alice");
    char *hash = db_text("SELECT password_hash FROM specus_management_user WHERE username = ?", "alice");
    CHECK(stored_key != NULL && strcmp(stored_key, expected_key) == 0, "binding key is not SHA-256(iss NUL sub)");
    CHECK(stored_issuer != NULL && strcmp(stored_issuer, issuer) == 0, "binding issuer not stored");
    CHECK(hash != NULL && strncmp(hash, "$pbkdf2-sha256$v=1$i=", strlen("$pbkdf2-sha256$v=1$i=")) == 0,
          "provisioned account has no real password hash");
    free(id_token);
    free(echoed);
    free(token_type);
    free(access);
    free(request);
    free(stored_key);
    free(stored_issuer);
    free(hash);
}

static void test_binding_follows_subject(void)
{
    /* preferred_username changed at the identity provider: still the same local account. */
    char *renamed = login_token("subject-alice", "alice-renamed");
    st_security_token_claims claims;
    CHECK(local_claims_of(renamed, &claims) == 0 && strcmp(claims.username, "alice") == 0,
          "a renamed identity provider account did not keep its bound user");
    char *row = db_text("SELECT username FROM specus_management_user WHERE username = ?", "alice-renamed");
    CHECK(row == NULL, "a rename created a second account");
    /* Subjects are case-sensitive: a different subject is a different identity. */
    char *upper = login_token("SUBJECT-ALICE", "alice-upper");
    CHECK(local_claims_of(upper, &claims) == 0 && strcmp(claims.username, "alice-upper") == 0,
          "subject comparison is not case-sensitive");
    free(renamed);
    free(row);
    free(upper);
}

static void test_binds_existing_user_once(void)
{
    create_user("bob", "default", "ADMIN", 1);
    char *token = login_token("subject-bob", "Bob");
    st_security_token_claims claims;
    CHECK(local_claims_of(token, &claims) == 0 && strcmp(claims.username, "bob") == 0
              && strcmp(claims.role, "ADMIN") == 0,
          "first OIDC login did not link the existing local user with its role");
    char expected_key[65];
    st_oidc_identity_key(issuer, "subject-bob", expected_key);
    char *stored_key = db_text("SELECT oidc_identity_key FROM specus_management_user WHERE username = ?", "bob");
    CHECK(stored_key != NULL && strcmp(stored_key, expected_key) == 0, "existing user was not bound");
    claims_spec intruder = id_claims("subject-intruder", "bob", "nonce-intruder");
    CHECK(login_claims(key_main, "k1", &intruder) == 403
              && contains(response, "该 Certus 账号已禁用或与现有 Specus 账号绑定冲突")
              && !contains(response, "accessToken"),
          "a second identity took over a bound user");
    free(token);
    free(stored_key);
}

static void test_disabled_users_are_refused(void)
{
    create_user("carol", "default", "USER", 0);
    claims_spec carol = id_claims("subject-carol", "carol", "nonce-carol");
    CHECK(login_claims(key_main, "k1", &carol) == 403, "a disabled unbound user was linked");
    char *bound = db_text("SELECT oidc_identity_key FROM specus_management_user WHERE username = ?", "carol");
    CHECK(bound == NULL || *bound == '\0', "a disabled user was bound");

    char *alice = login_token("subject-alice", "alice");
    CHECK(alice != NULL, "alice cannot log in");
    set_enabled("alice", 0);
    claims_spec again = id_claims("subject-alice", "alice", "nonce-disabled");
    CHECK(login_claims(key_main, "k1", &again) == 403, "a disabled bound user logged in");
    CHECK(alice != NULL && admin_request("GET", "/api/admin/me", alice) == 403,
          "a disabled user's earlier local token still works");
    set_enabled("alice", 1);
    CHECK(alice != NULL && admin_request("GET", "/api/admin/me", alice) == 200,
          "re-enabled user's token does not work again");
    free(bound);
    free(alice);
}

static void test_refused_usernames(void)
{
    char long_name[82];
    memset(long_name, 'x', 81U);
    long_name[81] = '\0';
    create_user("dora", "tenant-b", "USER", 1);
    const char *names[] = {"admin", "ADMIN", NULL, "   ", long_name, "dora"};
    const char *labels[] = {
        "preferred_username equal to the built-in admin was accepted",
        "preferred_username equal to the built-in admin in other case was accepted",
        "an ID token without preferred_username was accepted",
        "a blank preferred_username was accepted",
        "an 81-character preferred_username was accepted",
        "a same-named user of another tenant was linked or duplicated"
    };
    for (size_t i = 0U; i < sizeof(names) / sizeof(names[0]); ++i) {
        char *subject = format("subject-refused-%zu", i);
        claims_spec spec = id_claims(subject, names[i], "nonce-refused");
        CHECK(login_claims(key_main, "k1", &spec) == 403
                  && contains(response, "该 Certus 账号已禁用或与现有 Specus 账号绑定冲突"),
              labels[i]);
        free(subject);
    }
    char *dora_tenant = db_text("SELECT tenant_id FROM specus_management_user WHERE username = ?", "dora");
    CHECK(dora_tenant != NULL && strcmp(dora_tenant, "tenant-b") == 0, "the other tenant's user changed");
    free(dora_tenant);

    /* Java stores issuer and subject in 255-character columns and refuses longer values. */
    char long_subject[257];
    memset(long_subject, 's', 256U);
    long_subject[256] = '\0';
    claims_spec long_spec = id_claims(long_subject, "long-subject-user", "nonce-long");
    CHECK(login_claims(key_main, "k1", &long_spec) == 403, "a 256-character subject was bound");
    char *created = db_text("SELECT username FROM specus_management_user WHERE username = ?", "long-subject-user");
    CHECK(created == NULL, "a refused identity still created an account");
    free(created);
}

static void test_nonce_is_required_and_bound(void)
{
    claims_spec spec = id_claims("subject-alice", "alice", "nonce-in-token");
    char *token = make_token(key_main, "k1", &spec);
    CHECK(login_with(token, "nonce-in-request") == 502
              && contains(response, "OIDC ID Token 身份或 nonce 校验失败")
              && !contains(response, "accessToken"),
          "an ID token with another login's nonce was accepted");
    CHECK(login_with(token, "NONCE-IN-TOKEN") == 502, "nonce comparison ignores case");
    CHECK(login_with(token, "nonce-in-token ") == 502, "nonce comparison trims");
    free(token);

    claims_spec without = id_claims("subject-alice", "alice", NULL);
    token = make_token(key_main, "k1", &without);
    CHECK(login_with(token, "nonce-expected") == 502
              && contains(response, "OIDC ID Token 身份或 nonce 校验失败"),
          "an ID token without nonce was accepted");
    free(token);

    /* The request must carry the nonce; the one-time code is not spent without it. */
    claims_spec valid = id_claims("subject-alice", "alice", "nonce-kept");
    token = make_token(key_main, "k1", &valid);
    char *code = next_code();
    char *body = format("{\"id_token\":\"%s\",\"token_type\":\"Bearer\"}", token);
    idp_add_code(code, 200, body);
    int before = idp_token_requests();
    CHECK(redeem(code, VERIFIER, NULL) == 400 && contains(response, "缺少 code、code_verifier 或 nonce"),
          "a callback without nonce was not refused");
    CHECK(redeem(code, VERIFIER, "   ") == 400, "a blank nonce was not refused");
    CHECK(redeem(code, "", "nonce-kept") == 400, "a missing code_verifier was not refused");
    CHECK(redeem("", VERIFIER, "nonce-kept") == 400, "a missing code was not refused");
    CHECK(idp_token_requests() == before, "the token endpoint was called without a nonce");
    CHECK(redeem(code, VERIFIER, "nonce-kept") == 200, "the unspent code no longer works");
    free(token);
    free(code);
    free(body);
}

static void test_issuer_audience_and_azp(void)
{
    char *issuer_slash = format("%s/", issuer);
    struct {
        const char *iss;
        const char *aud;
        const char *azp;
        int expected;
        const char *label;
    } cases[] = {
        {"http://evil.example", "\"" CLIENT_ID "\"", NULL, 502, "a foreign issuer was accepted"},
        {issuer_slash, "\"" CLIENT_ID "\"", NULL, 502, "issuer comparison is not exact"},
        {NULL, "\"" CLIENT_ID "\"", NULL, 502, "a token without iss was accepted"},
        {issuer, "\"other-client\"", NULL, 502, "a token for another client was accepted"},
        {issuer, NULL, NULL, 502, "a token without aud was accepted"},
        {issuer, "[\"other-client\",\"" CLIENT_ID "\"]", NULL, 502, "several audiences without azp were accepted"},
        {issuer, "[\"other-client\",\"" CLIENT_ID "\"]", "other-client", 502, "azp naming another client was accepted"},
        {issuer, "\"" CLIENT_ID "\"", "other-client", 502, "a single audience with a foreign azp was accepted"},
        {issuer, "[\"other-client\",\"" CLIENT_ID "\"]", CLIENT_ID, 200, "several audiences with azp were refused"},
        {issuer, "[\"" CLIENT_ID "\"]", CLIENT_ID, 200, "an audience array with matching azp was refused"},
        {issuer, "\"" CLIENT_ID "\"", "", 200, "a single audience with an empty azp was refused"},
        {issuer, "[\"" CLIENT_ID "\",17]", NULL, 502, "an aud array holding a number was accepted"},
    };
    for (size_t i = 0U; i < sizeof(cases) / sizeof(cases[0]); ++i) {
        claims_spec spec = id_claims("subject-alice", "alice", "nonce-aud");
        spec.iss = cases[i].iss;
        spec.aud = cases[i].aud;
        spec.azp = cases[i].azp;
        int status = login_claims(key_main, "k1", &spec);
        CHECK(status == cases[i].expected, cases[i].label);
        if (cases[i].expected == 502) {
            CHECK(contains(response, "OIDC ID Token 校验失败"), "issuer/audience failure has the wrong error");
        }
    }
    free(issuer_slash);

    /* OidcController's own identity check, after the decoder accepted the token. */
    claims_spec no_subject = id_claims(NULL, "alice", "nonce-sub");
    CHECK(login_claims(key_main, "k1", &no_subject) == 502
              && contains(response, "OIDC ID Token 身份或 nonce 校验失败"),
          "an ID token without sub was accepted");
    no_subject.sub = "   ";
    CHECK(login_claims(key_main, "k1", &no_subject) == 502
              && contains(response, "OIDC ID Token 身份或 nonce 校验失败"),
          "an ID token with a blank sub was accepted");
}

static void test_expiry_and_not_before(void)
{
    struct {
        long long exp_offset;
        int omit_exp;
        const char *exp_raw;
        int has_nbf;
        long long nbf_offset;
        int expected;
        const char *label;
    } cases[] = {
        {-120, 0, NULL, 0, 0, 502, "an ID token expired two minutes ago was accepted"},
        {-30, 0, NULL, 0, 0, 200, "an ID token within the 60 s clock skew was refused"},
        {0, 1, NULL, 0, 0, 502, "an ID token without exp was accepted"},
        {0, 0, "\"4102444800\"", 0, 0, 502, "an exp written as a string was accepted"},
        {300, 0, NULL, 1, 300, 502, "an ID token not valid for five minutes was accepted"},
        {300, 0, NULL, 1, 30, 200, "an nbf within the clock skew was refused"},
    };
    for (size_t i = 0U; i < sizeof(cases) / sizeof(cases[0]); ++i) {
        claims_spec spec = id_claims("subject-alice", "alice", "nonce-time");
        spec.exp_offset = cases[i].exp_offset;
        spec.omit_exp = cases[i].omit_exp;
        spec.exp_raw = cases[i].exp_raw;
        spec.has_nbf = cases[i].has_nbf;
        spec.nbf_offset = cases[i].nbf_offset;
        CHECK(login_claims(key_main, "k1", &spec) == cases[i].expected, cases[i].label);
        if (cases[i].expected == 502) {
            CHECK(contains(response, "OIDC ID Token 校验失败"), "time failure has the wrong error");
        }
    }
}

static void test_signature_and_key_selection(void)
{
    claims_spec spec = id_claims("subject-alice", "alice", "nonce-sig");
    char *payload = claims_json(&spec);

    int hits = idp_jwks_hits();
    CHECK(login_claims(key_main, "missing-kid", &spec) == 502 && contains(response, "OIDC ID Token 校验失败"),
          "a token whose kid is not in the JWKS was accepted");
    CHECK(idp_jwks_hits() == hits + 1, "an unknown kid did not refetch the JWKS exactly once");

    CHECK(login_claims(key_attacker, "k1", &spec) == 502, "a token signed by an unpublished key was accepted");
    CHECK(login_claims(key_main, NULL, &spec) == 200, "a token without kid was not checked against every key");
    CHECK(login_claims(key_main, "", &spec) == 502, "an empty kid matched a key with another kid");

    /* Payload swapped after signing. */
    char *token = make_token(key_main, "k1", &spec);
    claims_spec other = id_claims("subject-bob", "bob", "nonce-sig");
    char *other_payload_json = claims_json(&other);
    char *other_payload = base64url_text(other_payload_json);
    char *first_dot = strchr(token, '.');
    char *second_dot = first_dot == NULL ? NULL : strchr(first_dot + 1, '.');
    if (first_dot != NULL && second_dot != NULL) {
        *first_dot = '\0';
        char *tampered = format("%s.%s%s", token, other_payload, second_dot);
        CHECK(login_with(tampered, "nonce-sig") == 502, "a tampered payload was accepted");
        free(tampered);
    }
    free(token);
    free(other_payload_json);
    free(other_payload);

    /* Algorithms Java does not admit. */
    char *none_header = base64url_text("{\"alg\":\"none\",\"kid\":\"k1\"}");
    char *none_payload = base64url_text(payload);
    char *unsigned_token = format("%s.%s.", none_header, none_payload);
    CHECK(login_with(unsigned_token, "nonce-sig") == 502, "an unsigned token was accepted");
    unsigned char *public_der = NULL;
    int public_der_len = i2d_PUBKEY(key_main, &public_der);
    CHECK(public_der_len > 0, "public key encoding failed");
    char *confused = sign_hs256(public_der, (size_t)(public_der_len > 0 ? public_der_len : 0),
                                "{\"alg\":\"HS256\",\"kid\":\"k1\"}", payload);
    CHECK(login_with(confused, "nonce-sig") == 502, "HS256 keyed with the RSA public key was accepted");
    char *es256 = sign_jwt(key_ec, "{\"alg\":\"ES256\",\"kid\":\"ec1\"}", payload);
    CHECK(login_with(es256, "nonce-sig") == 502, "an ES256 token was accepted although Java admits only RS256");
    /* A valid RS256 signature under a header naming another algorithm. */
    char *relabelled = sign_jwt(key_main, "{\"alg\":\"RS384\",\"kid\":\"k1\"}", payload);
    CHECK(login_with(relabelled, "nonce-sig") == 502, "a token whose header names RS384 was accepted");
    free(relabelled);
    relabelled = sign_jwt(key_main, "{\"alg\":\"rs256\",\"kid\":\"k1\"}", payload);
    CHECK(login_with(relabelled, "nonce-sig") == 502, "the alg comparison is not exact");
    free(relabelled);
    CHECK(login_claims(key_weak, "weak", &spec) == 502, "a token signed by a 1024-bit published key was accepted");
    char *critical = sign_jwt(key_main, "{\"alg\":\"RS256\",\"kid\":\"k1\",\"crit\":[\"exp\"]}", payload);
    CHECK(login_with(critical, "nonce-sig") == 502, "a token with a critical header was accepted");
    claims_spec duplicated = id_claims("subject-alice", "alice", "nonce-sig");
    duplicated.extra = "\"sub\":\"subject-bob\"";
    CHECK(login_claims(key_main, "k1", &duplicated) == 502, "a token with a repeated sub claim was accepted");

    free(payload);
    free(none_header);
    free(none_payload);
    free(unsigned_token);
    OPENSSL_free(public_der);
    free(confused);
    free(es256);
    free(critical);
}

static void test_key_rotation_and_refetch_cooldown(void)
{
    st_oidc_jwks_reset();
    st_oidc_jwks_set_refresh_cooldown_ms(60000);
    idp_publish(jwk_main, NULL, NULL, NULL);
    int hits = idp_jwks_hits();
    claims_spec spec = id_claims("subject-alice", "alice", "nonce-rotate");
    CHECK(login_claims(key_main, "k1", &spec) == 200 && idp_jwks_hits() == hits + 1,
          "the first validation did not fetch the JWKS once");
    CHECK(login_claims(key_main, "k1", &spec) == 200 && idp_jwks_hits() == hits + 1,
          "a cached key was fetched again");

    idp_publish(jwk_main, jwk_next, NULL, NULL);
    CHECK(login_claims(key_next, "k2", &spec) == 502 && idp_jwks_hits() == hits + 1,
          "an unknown kid refetched the JWKS inside the cooldown");
    CHECK(login_claims(key_main, "random-kid", &spec) == 502 && idp_jwks_hits() == hits + 1,
          "random kids refetched the JWKS inside the cooldown");

    st_oidc_jwks_set_refresh_cooldown_ms(0);
    CHECK(login_claims(key_next, "k2", &spec) == 200 && idp_jwks_hits() == hits + 2,
          "a rotated-in key was not picked up by one refetch");

    /* No usable keys, or no JWKS at all: nothing verifies. */
    st_oidc_jwks_reset();
    idp_set_jwks("{\"keys\":[]}", 500);
    CHECK(login_claims(key_main, "k1", &spec) == 502 && contains(response, "OIDC ID Token 校验失败"),
          "a token was accepted while the JWKS endpoint failed");
    st_oidc_jwks_reset();
    idp_publish(jwk_ec, jwk_weak, NULL, NULL);
    CHECK(login_claims(key_main, "k1", &spec) == 502, "a JWKS without usable RSA keys verified a token");

    st_oidc_jwks_reset();
    idp_publish(jwk_main, jwk_next, jwk_weak, jwk_ec);
}

static void test_callback_replay_is_refused(void)
{
    /* state never reaches the server: the SPA compares it with its sessionStorage copy and drops
     * it after one use. Replaying the callback therefore means redeeming the same code again,
     * which the identity provider refuses, and the server must not mint a token for it. */
    claims_spec spec = id_claims("subject-alice", "alice", "nonce-replay");
    char *token = make_token(key_main, "k1", &spec);
    char *code = next_code();
    char *body = format("{\"access_token\":\"idp-access-token\",\"id_token\":\"%s\",\"token_type\":\"Bearer\"}", token);
    idp_add_code(code, 200, body);
    int before = idp_token_requests();
    CHECK(redeem(code, VERIFIER, "nonce-replay") == 200, "the first redemption failed");
    CHECK(redeem(code, VERIFIER, "nonce-replay") == 502
              && contains(response, "\"error\":\"invalid_grant\"")
              && !contains(response, "accessToken"),
          "a replayed callback produced a token");
    CHECK(idp_token_requests() == before + 2, "the replay did not reach the token endpoint");
    free(token);
    free(code);
    free(body);
}

static void test_tenant_claim_does_not_choose_tenant(void)
{
    setenv("SPECUS_OIDC_TENANT_CLAIM", "org", 1);
    claims_spec spec = id_claims("subject-alice", "alice", "nonce-tenant");
    spec.extra = "\"org\":\"tenant-evil\",\"tenant_id\":\"tenant-evil\",\"role\":\"ADMIN\"";
    CHECK(login_claims(key_main, "k1", &spec) == 200, "login with tenant claims failed");
    char *access = access_token_of(response);
    st_security_token_claims claims;
    CHECK(local_claims_of(access, &claims) == 0 && strcmp(claims.tenant_id, "default") == 0
              && strcmp(claims.role, "USER") == 0,
          "ID token claims chose the tenant or role");
    CHECK(access != NULL && admin_request("GET", "/api/admin/me", access) == 200
              && contains(response, "\"tenantId\":\"default\"") && contains(response, "\"role\":\"USER\""),
          "the management API saw a tenant from the ID token");
    unsetenv("SPECUS_OIDC_TENANT_CLAIM");
    free(access);
}

static void test_direct_bearer_tokens(void)
{
    claims_spec spec = id_claims("subject-alice", NULL, NULL);
    spec.aud = "\"" RESOURCE_AUDIENCE "\"";
    spec.extra = "\"tenant_id\":\"tenant-evil\",\"role\":\"ADMIN\"";
    char *alice = make_token(key_main, "k1", &spec);

    unsetenv("SPECUS_OIDC_AUDIENCE");
    int hits = idp_jwks_hits();
    CHECK(admin_request("GET", "/api/admin/me", alice) == 401, "a bearer was accepted without a resource audience");
    CHECK(idp_jwks_hits() == hits, "a bearer without a configured audience fetched the JWKS");

    setenv("SPECUS_OIDC_AUDIENCE", RESOURCE_AUDIENCE, 1);
    CHECK(admin_request("GET", "/api/admin/me", alice) == 200
              && contains(response, "\"username\":\"alice\"")
              && contains(response, "\"tenantId\":\"default\"")
              && contains(response, "\"role\":\"USER\""),
          "a bound bearer did not resolve to its local user, tenant and role");
    CHECK(admin_request("GET", "/api/admin/users", alice) == 403, "a USER bearer reached an admin endpoint");
    CHECK(admin_request("POST", "/auth/refresh", alice) == 400
              && contains(response, "OIDC 令牌不能通过该端点续期"),
          "an identity provider token was renewed");

    claims_spec bob_spec = id_claims("subject-bob", NULL, NULL);
    bob_spec.aud = "[\"" RESOURCE_AUDIENCE "\",\"" CLIENT_ID "\"]";
    char *bob = make_token(key_main, "k1", &bob_spec);
    CHECK(admin_request("GET", "/api/admin/users", bob) == 200, "a bound ADMIN bearer was refused");

    claims_spec client_spec = id_claims("subject-alice", NULL, NULL);
    char *client_token = make_token(key_main, "k1", &client_spec);
    CHECK(admin_request("GET", "/api/admin/me", client_token) == 401,
          "an ID token for the browser client was accepted as an API bearer");

    claims_spec expired_spec = spec;
    expired_spec.exp_offset = -300;
    char *expired = make_token(key_main, "k1", &expired_spec);
    CHECK(admin_request("GET", "/api/admin/me", expired) == 401, "an expired bearer was accepted");

    claims_spec stranger_spec = spec;
    stranger_spec.sub = "subject-never-logged-in";
    char *stranger = make_token(key_main, "k1", &stranger_spec);
    CHECK(admin_request("GET", "/api/admin/me", stranger) == 403
              && contains(response, "账号未绑定、已禁用或权限已撤销"),
          "an unbound bearer was not refused with 403");
    CHECK(admin_request("POST", "/auth/refresh", stranger) == 400, "refresh of an unbound bearer was not 400");

    char *forged = make_token(key_attacker, "k1", &spec);
    CHECK(admin_request("GET", "/api/admin/me", forged) == 401, "a forged bearer was accepted");

    hits = idp_jwks_hits();
    CHECK(admin_request("GET", "/api/admin/me", "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ4In0.c2ln") == 401,
          "an HS512 bearer was accepted");
    CHECK(idp_jwks_hits() == hits, "an HS* bearer was sent to the OIDC decoder");

    set_enabled("alice", 0);
    CHECK(admin_request("GET", "/api/admin/me", alice) == 403, "a disabled user's bearer was accepted");
    set_enabled("alice", 1);
    unsetenv("SPECUS_OIDC_AUDIENCE");
    free(alice);
    free(bob);
    free(client_token);
    free(expired);
    free(stranger);
    free(forged);
}

static void test_confidential_client(void)
{
    setenv("SPECUS_OIDC_CLIENT_SECRET", "client-secret-value", 1);
    claims_spec spec = id_claims("subject-alice", "alice", "nonce-secret");
    CHECK(login_claims(key_main, "k1", &spec) == 200, "confidential client login failed");
    const char *credentials = CLIENT_ID ":client-secret-value";
    unsigned char basic[128];
    int basic_len = EVP_EncodeBlock(basic, (const unsigned char *)credentials, (int)strlen(credentials));
    char *expected = format("Authorization: Basic %.*s", basic_len, (const char *)basic);
    char *request = idp_last_token_request();
    CHECK(contains(request, expected) && !contains(request, "client_id="),
          "a confidential client did not authenticate with HTTP Basic only");
    unsetenv("SPECUS_OIDC_CLIENT_SECRET");
    free(expected);
    free(request);
}

static void test_configuration_fails_closed(void)
{
    claims_spec spec = id_claims("subject-alice", "alice", "nonce-config");
    char *token = make_token(key_main, "k1", &spec);
    int before = idp_token_requests();

    unsetenv("SPECUS_OIDC_CLIENT_ID");
    CHECK(login_with(token, "nonce-config") == 503 && contains(response, "OIDC 未配置（缺少 client-id）"),
          "login without client id was not 503");
    setenv("SPECUS_OIDC_CLIENT_ID", "   ", 1);
    CHECK(login_with(token, "nonce-config") == 503, "a blank client id counted as configured");
    CHECK(idp_token_requests() == before, "the token endpoint was called without a client id");
    setenv("SPECUS_OIDC_CLIENT_ID", CLIENT_ID, 1);

    unsetenv("SPECUS_DATABASE_PATH");
    CHECK(login_with(token, "nonce-config") == 503 && idp_token_requests() == before,
          "login without a user store spent the code");
    setenv("SPECUS_DATABASE_PATH", db_path, 1);

    /* SecurityConfigOidcTests: an unset-looking issuer must not fall back to trusting anyone. */
    setenv("SPECUS_OIDC_ISSUER", "", 1);
    CHECK(login_with(token, "nonce-config") == 502 && contains(response, "OIDC ID Token 校验失败"),
          "an empty issuer setting did not fail closed");
    setenv("SPECUS_OIDC_ISSUER", " ", 1);
    CHECK(login_with(token, "nonce-config") == 502 && contains(response, "OIDC ID Token 校验失败"),
          "a blank issuer setting did not fail closed");
    setenv("SPECUS_OIDC_ISSUER", issuer, 1);

    char *jwks_uri = format("http://127.0.0.1:%d/jwks", idp.port);
    setenv("SPECUS_OIDC_JWK_SET_URI", " ", 1);
    CHECK(login_with(token, "nonce-config") == 503 && contains(response, "OIDC 校验服务不可用"),
          "a blank JWK Set URI did not fail closed");
    setenv("SPECUS_OIDC_JWK_SET_URI", jwks_uri, 1);

    char *code = next_code();
    idp_add_code(code, 200, "{\"access_token\":\"idp-access-token\",\"token_type\":\"Bearer\"}");
    CHECK(redeem(code, VERIFIER, "nonce-config") == 502 && contains(response, "OIDC 响应缺少 ID Token")
              && !contains(response, "idp-access-token"),
          "a token response without id_token was passed through");
    free(code);
    code = next_code();
    idp_add_code(code, 200, "not json");
    CHECK(redeem(code, VERIFIER, "nonce-config") == 502 && contains(response, "OIDC 令牌响应无法解析"),
          "an unparseable token response was not 502");
    free(code);
    code = next_code();
    idp_add_code(code, 400, "{\"error\":\"access_denied\",\"error_description\":\"user cancelled\"}");
    CHECK(redeem(code, VERIFIER, "nonce-config") == 502
              && contains(response, "\"error\":\"access_denied\"")
              && contains(response, "\"error_description\":\"user cancelled\""),
          "a token endpoint error was not relayed as 502");
    free(code);

    char *token_endpoint = format("http://127.0.0.1:%d/token", idp.port);
    setenv("SPECUS_OIDC_TOKEN_ENDPOINT", "http://127.0.0.1:1/token", 1);
    CHECK(login_with(token, "nonce-config") == 502 && contains(response, "无法连接 OIDC 令牌端点"),
          "an unreachable token endpoint was not 502");
    setenv("SPECUS_OIDC_TOKEN_ENDPOINT", "", 1);
    CHECK(login_with(token, "nonce-config") == 502, "an empty token endpoint fell back to a default");
    setenv("SPECUS_OIDC_TOKEN_ENDPOINT", token_endpoint, 1);
    CHECK(login_with(token, "nonce-config") == 200, "login does not recover after configuration is restored");
    free(token_endpoint);
    free(jwks_uri);
    free(token);
}

typedef struct {
    pthread_barrier_t *barrier;
    int index;
    int result;
} race_arg;

static void *race_bind(void *arg)
{
    race_arg *race = (race_arg *)arg;
    char subject[64];
    char key[65];
    snprintf(subject, sizeof(subject), "race-subject-%d", race->index);
    st_oidc_identity_key(issuer, subject, key);
    st_storage_management_user user;
    pthread_barrier_wait(race->barrier);
    race->result = st_storage_resolve_oidc_user(db_path, issuer, subject, key, "race", "default", NULL, &user);
    return NULL;
}

static void test_concurrent_first_logins_bind_once(void)
{
    create_user("race", "default", "USER", 1);
    enum { RACERS = 8 };
    pthread_t threads[RACERS];
    race_arg args[RACERS];
    pthread_barrier_t barrier;
    pthread_barrier_init(&barrier, NULL, RACERS);
    for (int i = 0; i < RACERS; ++i) {
        args[i].barrier = &barrier;
        args[i].index = i;
        args[i].result = -9;
        pthread_create(&threads[i], NULL, race_bind, &args[i]);
    }
    int winners = 0;
    int refused = 0;
    for (int i = 0; i < RACERS; ++i) {
        pthread_join(threads[i], NULL);
        winners += args[i].result == 0;
        refused += args[i].result == 1;
    }
    pthread_barrier_destroy(&barrier);
    CHECK(winners == 1 && refused == RACERS - 1, "concurrent first logins did not bind exactly one identity");
}

static void remove_database(void)
{
    char *journal = format("%s-journal", db_path);
    unlink(db_path);
    unlink(journal);
    free(journal);
}

int main(void)
{
    /* Talk to the fake identity provider directly even when the caller's shell sets a proxy. */
    const char *proxies[] = {"http_proxy", "HTTP_PROXY", "https_proxy", "HTTPS_PROXY", "all_proxy", "ALL_PROXY"};
    for (size_t i = 0U; i < sizeof(proxies) / sizeof(proxies[0]); ++i) {
        unsetenv(proxies[i]);
    }
    const char *tmp = getenv("TMPDIR");
    snprintf(db_path, sizeof(db_path), "%s/specus-c-oidc-%ld.db",
             tmp != NULL && *tmp != '\0' ? tmp : "/tmp", (long)getpid());
    remove_database();

    key_main = rsa_key(2048U);
    key_next = rsa_key(2048U);
    key_attacker = rsa_key(2048U);
    key_weak = rsa_key(1024U);
    key_ec = ec_key();
    jwk_main = rsa_jwk(key_main, "k1");
    jwk_next = rsa_jwk(key_next, "k2");
    jwk_weak = rsa_jwk(key_weak, "weak");
    jwk_ec = ec_jwk(key_ec, "ec1");

    if (idp_start() != 0) {
        fprintf(stderr, "fake identity provider failed to start\n");
        return 1;
    }
    snprintf(issuer, sizeof(issuer), "http://127.0.0.1:%d", idp.port);
    char *jwks_uri = format("http://127.0.0.1:%d/jwks", idp.port);
    char *token_endpoint = format("http://127.0.0.1:%d/token", idp.port);
    setenv("SPECUS_DATABASE_PATH", db_path, 1);
    setenv("SPECUS_DB_SEED_DEMO_CLIENT", "false", 1);
    setenv("SPECUS_AUTH_JWT_SECRET", JWT_SECRET, 1);
    unsetenv("SPECUS_AUTH_USERNAME");
    unsetenv("SPECUS_AUTH_PASSWORD");
    unsetenv("SPECUS_AUTH_TENANT_ID");
    unsetenv("SPECUS_AUTH_TOKEN_TTL_SECONDS");
    setenv("SPECUS_OIDC_ISSUER", issuer, 1);
    setenv("SPECUS_OIDC_JWK_SET_URI", jwks_uri, 1);
    setenv("SPECUS_OIDC_TOKEN_ENDPOINT", token_endpoint, 1);
    setenv("SPECUS_OIDC_CLIENT_ID", CLIENT_ID, 1);
    setenv("SPECUS_OIDC_REDIRECT_URI", "http://127.0.0.1:8088/", 1);
    unsetenv("SPECUS_OIDC_CLIENT_SECRET");
    unsetenv("SPECUS_OIDC_AUDIENCE");
    unsetenv("SPECUS_OIDC_TENANT_CLAIM");
    unsetenv("SPECUS_OIDC_CA_CERTIFICATE_PATH");
    if (st_storage_init(db_path, 0) != 0) {
        fprintf(stderr, "database init failed\n");
        return 1;
    }
    idp_publish(jwk_main, jwk_next, jwk_weak, jwk_ec);
    st_oidc_jwks_reset();
    st_oidc_jwks_set_refresh_cooldown_ms(0);

    test_login_issues_local_token();
    test_binding_follows_subject();
    test_binds_existing_user_once();
    test_disabled_users_are_refused();
    test_refused_usernames();
    test_nonce_is_required_and_bound();
    test_issuer_audience_and_azp();
    test_expiry_and_not_before();
    test_signature_and_key_selection();
    test_key_rotation_and_refetch_cooldown();
    test_callback_replay_is_refused();
    test_tenant_claim_does_not_choose_tenant();
    test_direct_bearer_tokens();
    test_confidential_client();
    test_configuration_fails_closed();
    test_concurrent_first_logins_bind_once();

    idp_stop();
    st_oidc_jwks_reset();
    remove_database();
    free(jwks_uri);
    free(token_endpoint);
    free(jwk_main);
    free(jwk_next);
    free(jwk_weak);
    free(jwk_ec);
    EVP_PKEY_free(key_main);
    EVP_PKEY_free(key_next);
    EVP_PKEY_free(key_attacker);
    EVP_PKEY_free(key_weak);
    EVP_PKEY_free(key_ec);
    if (failures != 0) {
        fprintf(stderr, "oidc tests: %d of %d checks failed\n", failures, checks);
        return 1;
    }
    printf("oidc tests passed (%d checks)\n", checks);
    return 0;
}
