// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShuaiTunnel.Server.Data;

#nullable disable

namespace ShuaiTunnel.Server.Data.MySql.Migrations
{
    [DbContext(typeof(TunnelDbContext))]
    [Migration("20260710034231_AddClientMessagingAndTransfer")]
    partial class AddClientMessagingAndTransfer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.ClientAccount", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("client_name");

                    b.Property<int>("ConnectionRateLimitPerMinute")
                        .HasColumnType("int")
                        .HasColumnName("connection_rate_limit_per_minute");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("OwnerUsername")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("owner_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("password_hash");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientName")
                        .IsUnique();

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_tunnel_client_tenant");

                    b.HasIndex("TenantId", "OwnerUsername")
                        .HasDatabaseName("idx_tunnel_client_owner");

                    b.ToTable("tunnel_client_account", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.ClientCredential", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("api_key");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<int>("MaxOnlineInstances")
                        .HasColumnType("int")
                        .HasColumnName("max_online_instances");

                    b.Property<string>("OwnerUsername")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("owner_username");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("secret_hash");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique()
                        .HasDatabaseName("uk_client_credential_api_key");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_client_credential_tenant");

                    b.HasIndex("TenantId", "OwnerUsername")
                        .HasDatabaseName("idx_client_credential_owner");

                    b.ToTable("tunnel_client_credential", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.ClientDownloadLink", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Arch")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("arch");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("download_url");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("Implementation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("implementation");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("platform");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("idx_client_download_order");

                    b.HasIndex("Implementation")
                        .HasDatabaseName("idx_client_download_impl");

                    b.ToTable("client_download_link", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.ClientIdentity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("client_name");

                    b.Property<long>("CredentialId")
                        .HasColumnType("bigint")
                        .HasColumnName("credential_id");

                    b.Property<string>("FirstSeenAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("Hostname")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("hostname");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("MachineFingerprint")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("machine_fingerprint");

                    b.Property<string>("OsUser")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("os_user");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("idx_client_identity_client");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_client_identity_tenant");

                    b.HasIndex("CredentialId", "MachineFingerprint", "OsUser")
                        .IsUnique()
                        .HasDatabaseName("uk_client_identity_machine_user");

                    b.ToTable("tunnel_client_identity", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.ClientSession", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("channel_id");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("client_name");

                    b.Property<string>("ClientVersion")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("client_version");

                    b.Property<long>("CredentialId")
                        .HasColumnType("bigint")
                        .HasColumnName("credential_id");

                    b.Property<string>("DisconnectedAt")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("disconnected_at");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("expires_at");

                    b.Property<string>("Hostname")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("hostname");

                    b.Property<string>("HttpLoginAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("http_login_at");

                    b.Property<long>("IdentityId")
                        .HasColumnType("bigint")
                        .HasColumnName("identity_id");

                    b.Property<string>("JavaVersion")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("java_version");

                    b.Property<string>("LocalAddresses")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("local_addresses");

                    b.Property<string>("MachineFingerprint")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("machine_fingerprint");

                    b.Property<bool>("MessageAttachmentsCapable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("message_attachments_capable");

                    b.Property<long>("MessageMaxAttachmentBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("message_max_attachment_bytes");

                    b.Property<bool>("MessageMediaPreviewCapable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("message_media_preview_capable");

                    b.Property<bool>("MessageReceiveCapable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("message_receive_capable");

                    b.Property<bool>("MessageSendCapable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("message_send_capable");

                    b.Property<string>("NettyConnectedAt")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("netty_connected_at");

                    b.Property<string>("OsArch")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("os_arch");

                    b.Property<string>("OsName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("os_name");

                    b.Property<string>("OsUser")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("os_user");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("os_version");

                    b.Property<string>("RemoteAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("remote_address");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("idx_client_session_token");

                    b.HasIndex("CredentialId", "Status")
                        .HasDatabaseName("idx_client_session_credential_status");

                    b.HasIndex("CredentialId", "MachineFingerprint", "OsUser", "Status")
                        .HasDatabaseName("idx_client_session_machine_status");

                    b.ToTable("tunnel_client_session", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.ConnectionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("channel_id");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("client_name");

                    b.Property<string>("ConnectedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("connected_at");

                    b.Property<string>("DisconnectReason")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("disconnect_reason");

                    b.Property<string>("DisconnectedAt")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("disconnected_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("RemoteAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("remote_address");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("success");

                    b.Property<string>("TenantId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedAt")
                        .HasDatabaseName("idx_tunnel_connection_connected_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_tunnel_connection_tenant");

                    b.HasIndex("ClientId", "ConnectedAt")
                        .HasDatabaseName("idx_tunnel_connection_client_time");

                    b.ToTable("tunnel_connection_record", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.ConnectionStat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("client_name");

                    b.Property<long>("FailureCount")
                        .HasColumnType("bigint")
                        .HasColumnName("failure_count");

                    b.Property<string>("StatMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("stat_month");

                    b.Property<long>("SuccessCount")
                        .HasColumnType("bigint")
                        .HasColumnName("success_count");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tenant_id");

                    b.Property<long>("TotalCount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_count");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientName");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_tunnel_connection_stat_tenant");

                    b.HasIndex("TenantId", "ClientName", "StatMonth")
                        .IsUnique()
                        .HasDatabaseName("uk_tunnel_connection_stat");

                    b.ToTable("tunnel_connection_stat", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.HttpRouteMapping", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("client_name");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("created_at");

                    b.Property<bool>("DetailCaptureEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("detail_capture_enabled");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<bool>("PathRewriteEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("path_rewrite_enabled");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("route");

                    b.Property<string>("TargetBaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("target_base_url");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientId", "Route")
                        .IsUnique();

                    b.ToTable("http_route_mapping", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.HttpTrafficExchange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CapturedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("captured_at");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("client_name");

                    b.Property<long>("ElapsedMs")
                        .HasColumnType("bigint")
                        .HasColumnName("elapsed_ms");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("error");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("method");

                    b.Property<string>("RawQuery")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("raw_query");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("relative_path");

                    b.Property<string>("RemoteAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("remote_address");

                    b.Property<long>("RequestBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("request_bytes");

                    b.Property<string>("RequestContentType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("request_content_type");

                    b.Property<string>("RequestHeaders")
                        .HasMaxLength(8192)
                        .HasColumnType("varchar(8192)")
                        .HasColumnName("request_headers");

                    b.Property<string>("RequestPreviewHex")
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("request_preview_hex");

                    b.Property<string>("RequestPreviewText")
                        .HasColumnType("longtext")
                        .HasColumnName("request_preview_text");

                    b.Property<bool>("RequestTruncated")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("request_truncated");

                    b.Property<long?>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("resource_name");

                    b.Property<string>("ResponseBodyType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("response_body_type");

                    b.Property<long>("ResponseBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("response_bytes");

                    b.Property<string>("ResponseContentType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("response_content_type");

                    b.Property<string>("ResponseHeaders")
                        .HasMaxLength(8192)
                        .HasColumnType("varchar(8192)")
                        .HasColumnName("response_headers");

                    b.Property<string>("ResponsePreviewHex")
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("response_preview_hex");

                    b.Property<string>("ResponsePreviewText")
                        .HasColumnType("longtext")
                        .HasColumnName("response_preview_text");

                    b.Property<bool>("ResponseTruncated")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("response_truncated");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("route");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int")
                        .HasColumnName("status_code");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("success");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt")
                        .HasDatabaseName("idx_http_traffic_captured_at");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("idx_http_traffic_client");

                    b.HasIndex("ResponseBodyType")
                        .HasDatabaseName("idx_http_traffic_body_type");

                    b.HasIndex("Route")
                        .HasDatabaseName("idx_http_traffic_route");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_http_traffic_tenant");

                    b.ToTable("tunnel_http_traffic_exchange", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.ManagementUser", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("username");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("updated_at");

                    b.HasKey("Username");

                    b.HasIndex("Role")
                        .HasDatabaseName("idx_management_user_role");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_management_user_tenant");

                    b.ToTable("tunnel_management_user", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.PeerMeshAcl", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("Allowed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("allowed");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("created_at");

                    b.Property<string>("OwnerUsername")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("owner_username");

                    b.Property<long>("SourceClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_client_id");

                    b.Property<string>("SourceClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("source_client_name");

                    b.Property<long>("TargetClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_client_id");

                    b.Property<string>("TargetClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("target_client_name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SourceClientId")
                        .HasDatabaseName("idx_peer_mesh_acl_source");

                    b.HasIndex("TenantId", "TargetClientId")
                        .HasDatabaseName("idx_peer_mesh_acl_target");

                    b.HasIndex("TenantId", "SourceClientId", "TargetClientId")
                        .IsUnique()
                        .HasDatabaseName("uk_peer_mesh_acl_pair");

                    b.ToTable("peer_mesh_acl", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.PeerMeshDevice", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Cidr")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("cidr");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("client_name");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("LastEndpoint")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_endpoint");

                    b.Property<string>("LastSeenAt")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("NatType")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nat_type");

                    b.Property<string>("OwnerUsername")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("owner_username");

                    b.Property<string>("PublicKey")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("public_key");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("updated_at");

                    b.Property<string>("VirtualDeviceError")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("virtual_device_error");

                    b.Property<string>("VirtualDeviceMode")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("virtual_device_mode");

                    b.Property<string>("VirtualDeviceName")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("virtual_device_name");

                    b.Property<string>("VirtualDeviceStatus")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("virtual_device_status");

                    b.Property<string>("VirtualDeviceUpdatedAt")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("virtual_device_updated_at");

                    b.Property<string>("VirtualIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("virtual_ip");

                    b.HasKey("Id");

                    b.HasIndex("ClientName")
                        .HasDatabaseName("idx_peer_mesh_device_client_name");

                    b.HasIndex("TenantId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("uk_peer_mesh_device_client");

                    b.HasIndex("TenantId", "OwnerUsername")
                        .HasDatabaseName("idx_peer_mesh_device_owner");

                    b.HasIndex("TenantId", "VirtualIp")
                        .IsUnique()
                        .HasDatabaseName("uk_peer_mesh_device_ip");

                    b.ToTable("peer_mesh_device", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.PeerMeshSession", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ClosedAt")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("closed_at");

                    b.Property<long>("DirectBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("direct_bytes");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("expires_at");

                    b.Property<string>("LastTrafficAt")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("last_traffic_at");

                    b.Property<string>("LocalEndpoint")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("local_endpoint");

                    b.Property<string>("PathType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("path_type");

                    b.Property<long>("RelayBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("relay_bytes");

                    b.Property<string>("RemoteEndpoint")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("remote_endpoint");

                    b.Property<long?>("RttMillis")
                        .HasColumnType("bigint")
                        .HasColumnName("rtt_millis");

                    b.Property<long>("SourceClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_client_id");

                    b.Property<string>("SourceClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("source_client_name");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<long>("TargetClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_client_id");

                    b.Property<string>("TargetClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("target_client_name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_peer_mesh_session_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_peer_mesh_session_tenant");

                    b.HasIndex("TenantId", "SourceClientId")
                        .HasDatabaseName("idx_peer_mesh_session_source");

                    b.HasIndex("TenantId", "TargetClientId")
                        .HasDatabaseName("idx_peer_mesh_session_target");

                    b.ToTable("peer_mesh_session", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.ResourceTrafficUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("client_name");

                    b.Property<long>("DownloadBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("download_bytes");

                    b.Property<long?>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("resource_key");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("resource_name");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("resource_type");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("updated_at");

                    b.Property<long>("UploadBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("upload_bytes");

                    b.Property<string>("UsageDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("usage_date");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("idx_resource_traffic_client");

                    b.HasIndex("ResourceType")
                        .HasDatabaseName("idx_resource_traffic_type");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_resource_traffic_tenant");

                    b.HasIndex("UsageDate")
                        .HasDatabaseName("idx_resource_traffic_date");

                    b.HasIndex("TenantId", "ClientId", "ResourceType", "ResourceKey", "UsageDate")
                        .IsUnique()
                        .HasDatabaseName("uk_resource_traffic_resource_date");

                    b.ToTable("tunnel_resource_traffic_usage", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.TcpTrafficFrame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("channel_id");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("client_name");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("destination_address");

                    b.Property<int?>("DestinationPort")
                        .HasColumnType("int")
                        .HasColumnName("destination_port");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("frame_direction");

                    b.Property<long>("FrameIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("frame_index");

                    b.Property<string>("FrameTime")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("frame_time");

                    b.Property<int>("ListenPort")
                        .HasColumnType("int")
                        .HasColumnName("listen_port");

                    b.Property<long>("PayloadBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("payload_bytes");

                    b.Property<byte[]>("PayloadData")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("payload_data");

                    b.Property<string>("PayloadPreviewHex")
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("payload_preview_hex");

                    b.Property<string>("PayloadPreviewText")
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("payload_preview_text");

                    b.Property<string>("RemoteAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("remote_address");

                    b.Property<long?>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("resource_name");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_address");

                    b.Property<int?>("SourcePort")
                        .HasColumnType("int")
                        .HasColumnName("source_port");

                    b.Property<long>("StreamEndOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("stream_end_offset");

                    b.Property<long>("StreamOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("stream_offset");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("Truncated")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("truncated");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("idx_tcp_traffic_channel");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("idx_tcp_traffic_client");

                    b.HasIndex("FrameTime")
                        .HasDatabaseName("idx_tcp_traffic_frame_time");

                    b.HasIndex("ListenPort")
                        .HasDatabaseName("idx_tcp_traffic_listen_port");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_tcp_traffic_tenant");

                    b.HasIndex("TenantId", "ChannelId", "Direction", "StreamOffset")
                        .HasDatabaseName("idx_tcp_traffic_stream");

                    b.ToTable("tunnel_tcp_traffic_frame", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.TrafficUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("client_name");

                    b.Property<long>("DownloadBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("download_bytes");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("updated_at");

                    b.Property<long>("UploadBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("upload_bytes");

                    b.Property<string>("UsageDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("usage_date");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("idx_tunnel_traffic_client");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_tunnel_traffic_tenant");

                    b.HasIndex("ClientId", "UsageDate")
                        .IsUnique();

                    b.ToTable("tunnel_traffic_usage", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.TransferAttachment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("expires_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("mime_type");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("object_key");

                    b.Property<string>("OwnerUsername")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("owner_username");

                    b.Property<string>("RoomId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("room_id");

                    b.Property<string>("RoomTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("room_token_hash");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("scope");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("status");

                    b.Property<long?>("TargetClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_client_id");

                    b.Property<string>("TenantId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UploadExpiresAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("upload_expires_at");

                    b.Property<string>("UploadedAt")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt", "Status")
                        .HasDatabaseName("idx_transfer_attachment_expires");

                    b.HasIndex("Scope", "RoomId", "Id")
                        .HasDatabaseName("idx_transfer_attachment_room");

                    b.HasIndex("TenantId", "Scope", "Id")
                        .HasDatabaseName("idx_transfer_attachment_tenant");

                    b.ToTable("transfer_attachment", (string)null);
                });

            modelBuilder.Entity("ShuaiTunnel.Server.Data.Entities.TunnelMapping", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("client_name");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("created_at");

                    b.Property<bool>("DetailCaptureEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("detail_capture_enabled");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<int>("ListenPort")
                        .HasColumnType("int")
                        .HasColumnName("listen_port");

                    b.Property<string>("TargetAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("target_address");

                    b.Property<int>("TargetPort")
                        .HasColumnType("int")
                        .HasColumnName("target_port");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ListenPort")
                        .IsUnique();

                    b.ToTable("tunnel_mapping", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
